- name: Create Minecraft group
  group:
    name: "{{ minecraft_group }}"
    state: present
  register: group_create

- name: Create Minecraft user
  user:
    name: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    shell: /bin/bash
    create_home: yes
    home: "{{ minecraft_server_dir }}"
  register: user_create

- name: Create Minecraft server directory
  file:
    path: "{{ minecraft_server_dir }}"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: '0755'
  register: dir_create

- name: Create backup directory
  file:
    path: "{{ minecraft_backup_dir }}"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: '0755'
  when: backup_enabled | bool
  register: backup_dir_create 